version: '3'
services:
  my-app:
    image: 975049955606.dkr.ecr.ap-south-1.amazonaws.com/my-app:1.1
    ports:
      - 3000:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - anant-data:/data/db
  mongo-express:
    image: mongo-express
    ports: 
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo
volumes:
  anant-data:
    driver: local